version: '3.8'
services:
  mvs:
    build:
      context: .
      network: host
    volumes:
      - .:/workspace
    ports:
      - "8888:8888"  # 如果需要Jupyter notebook
    tty: true
    stdin_open: true
    command: tail -f /dev/null
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    dns:
      - 8.8.8.8
      - 8.8.4.4
    network_mode: "host"
    environment:
      - NVIDIA_VISIBLE_DEVICES=all